name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate config file
        run: |
          echo '{
            "token": "${{ secrets.PAT }}"
          }' > config.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
      - name: Push Changes to GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add database.xlsx
          git commit -m "Update database.xlsx via GitHub Actions" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/yitingchen00/skills-github-pages.git

