name: Update Excel File

on:
  workflow_dispatch:  # 允許手動觸發
  repository_dispatch:  # 允許前端 API 觸發
    types: [update-excel]  

jobs:
  update-excel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Decode Data
        run: |
          echo "${{ github.event.client_payload.data }}" | base64 --decode > database.xlsx

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add database.xlsx
          git commit -m "Update database.xlsx via GitHub Actions" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
