name: Update Excel File

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update-excel]

jobs:
  update-excel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}  # 使用 GitHub Secrets 儲存的 PAT

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Decode Data
        run: |
          echo "${{ github.event.client_payload.data }}" | base64 --decode > database.xlsx

      - name: Commit and Push Changes
        run: |
          git add database.xlsx
          git commit -m "Update database.xlsx via GitHub Actions" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/yitingchen00/skills-github-pages.git
